### ISSUE TITLE
Typos in White_2019_10_14_Linear_Regression_02.pdf.

### ISSUE THREAD

**Issue by stvhuang** [2019ChenGong/Machine-Learning-Notes#1]
In eq.11 to eq.17 (p.3), all the ![\prod_{i=i}^N](https://render.githubusercontent.com/render/math?math=%5Cprod_%7Bi%3Di%7D%5EN) should be ![\sum_{i=i}^N](https://render.githubusercontent.com/render/math?math=%5Csum_%7Bi%3Di%7D%5EN).

**Comment by 2019ChenGong** [comment]
Thank you! In here, we use log likelihood, so it is \prod not \sum.

**Comment by 2019ChenGong** [comment]
Thank you!

**Comment by 2019ChenGong** [comment]
I have changed it.
